server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com
  #    hostname: localhost # eureka服务端的实例名称 单机版
  client:
    # false 表示不向服务中心注册自己。
    register-with-eureka: false
    # false 表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      # 设置与eureka server 交互的地址查询服务和注册服务都需要依赖这个地址
      defultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  # 单机版
    #      defaultZone: http://eureka7002.com:7002/eureka/
  server:
    # 无情版 关闭自我保护机制，保证不可用服务被及时剔除
    enable-self-preservation: false
    # 检测服务时间
    eviction-interval-timer-in-ms: 2000